# Generated by Django 4.0.4 on 2022-05-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_basecontact_notificationsetting_userprofile_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='organizations',
            field=models.ManyToManyField(to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='signiture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='source',
            field=models.CharField(choices=[('em', 'Email'), ('go', 'Google'), ('ln', 'LinkedIn'), ('gh', 'Github')], default='em', max_length=2),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='updated_At',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='base_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.basecontact'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='notification_setting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.notificationsetting'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
