# Generated by Django 4.0.4 on 2022-05-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_baseuser_organizations_baseuser_signiture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='notification_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.notificationsetting'),
        ),
    ]
