# Generated by Django 4.0.4 on 2022-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_baseuser_notification_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='setting',
            field=models.CharField(choices=[('se', 'Send Email'), ('sp', 'Send Push')], max_length=2),
        ),
    ]
