# Generated by Django 4.0.4 on 2022-05-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_address_basecontact_notificationsetting_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/attachments')),
                ('is_resume', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ln', 'LinkedIn'), ('fb', 'Facebook'), ('is', 'Instragram'), ('tw', 'Twitter'), ('gi', 'Github'), ('tk', 'TikTok')], max_length=2)),
                ('link', models.URLField()),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('employeer', models.TextField()),
                ('currently_working', models.BooleanField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.qualificationchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('current_employeer', models.TextField(blank=True, null=True)),
                ('date_available', models.DateField(blank=True, null=True)),
                ('current_pay', models.CharField(blank=True, max_length=200, null=True)),
                ('desired_pay', models.CharField(blank=True, max_length=200, null=True)),
                ('best_contact_time', models.DateTimeField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('attachments', models.ManyToManyField(to='candidates.attachments')),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateprofile')),
                ('phones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.basecontact')),
                ('qualifications', models.ManyToManyField(to='candidates.candidatequalification')),
                ('social_medias', models.ManyToManyField(to='candidates.socialmedias')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidatesource')),
                ('work_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.workhistory')),
            ],
        ),
    ]
