# Generated by Django 4.0.4 on 2022-05-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_qualificationchecklist_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedias',
            new_name='SocialMedia',
        ),
    ]
