# Generated by Django 3.2.11 on 2022-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_rename_attachments_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='work_history',
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_history',
            field=models.ManyToManyField(to='candidates.WorkHistory'),
        ),
    ]
