# Generated by Django 4.0.4 on 2022-05-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('emails', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.color')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciton', models.CharField(choices=[('se', 'Send Email'), ('sc', 'Submit To Client'), ('st', 'Send Telegram Message'), ('ac', 'Add Calendar Entry'), ('wh', 'Send Webhook')], default='se', max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_type', models.CharField(choices=[('rq', 'Required'), ('do', 'Optional, on by Default'), ('df', 'Optional, off by Default')], default='df', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_composition_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.coreemail')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidates', models.ManyToManyField(to='candidates.candidate')),
                ('pipeline_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipelinesetup')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.color')),
            ],
        ),
        migrations.AddField(
            model_name='pipelinesetup',
            name='mapping_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_status', to='pipelines.pipelinestatus'),
        ),
        migrations.AddField(
            model_name='pipelinesetup',
            name='prerequisite_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_status', to='pipelines.pipelinestatus'),
        ),
        migrations.AddField(
            model_name='pipelinesetup',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='pipelines.pipelinestatus'),
        ),
        migrations.AddField(
            model_name='pipelinesetup',
            name='triggers',
            field=models.ManyToManyField(to='pipelines.trigger'),
        ),
    ]
