# Generated by Django 4.0.4 on 2022-05-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_alter_pipelineworkflow_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinesetup',
            name='prerequisite_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_status', to='pipelines.pipelinestatus'),
        ),
    ]
