# Generated by Django 4.0.4 on 2022-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_alter_pipelinesetup_prerequisite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinesetup',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='pipelines.trigger'),
        ),
    ]
