# Generated by Django 4.0.4 on 2022-05-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_contacts_and_more'),
        ('pipelines', '0005_pipelineworkflow_workflow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineworkflow',
            name='workflow_status',
        ),
        migrations.AddField(
            model_name='pipelinestatus',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
