# Generated by Django 3.2.11 on 2022-05-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_remove_pipelineworkflow_workflow_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinesetup',
            name='prerequisite_status',
        ),
        migrations.AddField(
            model_name='pipelinesetup',
            name='prerequisite_status',
            field=models.ManyToManyField(blank=True, null=True, related_name='prerequisite_status', to='pipelines.PipelineStatus'),
        ),
    ]
