# Generated by Django 4.0.4 on 2022-05-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
        ('accounts', '0003_baseuser_organizations_baseuser_signiture_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position_type', models.CharField(choices=[('rm', 'Remote'), ('fl', 'Full Time'), ('pt', 'Part Time'), ('fr', 'Freelance'), ('rl', 'With Relocation')], max_length=2)),
                ('start_date', models.DateField()),
                ('salary', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('max_rate', models.CharField(max_length=100)),
                ('openings', models.BigIntegerField()),
                ('remaining_openings', models.BigIntegerField()),
                ('hot', models.BooleanField()),
                ('publish', models.BooleanField(default=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joborders.jobdetail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('pipeline_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipelineworkflow')),
            ],
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joborders.jobordercategory'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joborders.jobordertype'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmember'),
        ),
    ]
