# Generated by Django 4.0.4 on 2022-05-22 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_address_basecontact_notificationsetting_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('default', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.color')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('ow', 'Is Owner'), ('ad', 'Is Admin'), ('ed', 'Is Editor'), ('ro', 'Read Only')], max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reachable', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.basecontact')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_pic', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('org_type', models.CharField(choices=[('st', 'Startup'), ('cm', 'Company'), ('hr', 'Hr Firm'), ('rf', 'Recuitment Firm')], max_length=2)),
                ('pipeline_template', models.CharField(choices=[('st', 'Startup'), ('cm', 'Company'), ('hr', 'Hr Firm'), ('rf', 'Recuitment Firm')], help_text='Default pipeline template to be created will be based on org type', max_length=2)),
                ('verified', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(to='organizations.organizationcontact')),
                ('members', models.ManyToManyField(to='organizations.organizationmember')),
                ('org_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationstatus')),
            ],
        ),
    ]
