# Generated by Django 4.0.4 on 2022-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='organizations.organizationcontact'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, to='organizations.organizationmember'),
        ),
    ]
