# Generated by Django 4.0.4 on 2022-05-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joborders', '0001_initial'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreemail',
            name='regarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joborders.joborder'),
        ),
    ]
